### ISSUE TITLE
Consider Python-related docsets (like NumPy) as corresponding to python filetype

### ISSUE THREAD

**Issue by petRUShka** [sunaku/vim-dasht#10]
I've installed NumPy and ScyPy docsets but if I use `<leader> K`dasht searches only in Python docsets whereas it should search in NumPy docset also.

Is it possible to force vim-dasht to search not only in maim docset but in related also?

**Comment by sunaku** [comment]
Please try this configuration snippet from the README:

```vim
  " When in Python, also search NumPy, SciPy, and Pandas:
  let g:dasht_filetype_docsets['python'] = ['(num|sci)py', 'pandas']
```

**Comment by petRUShka** [comment]
Sorry, my fault. I've missed it in README.
