### ISSUE TITLE
Not an editor command : Dasht in NeoVim v0.4.3

### ISSUE THREAD

**Issue by philipatc** [sunaku/vim-dasht#13]
I've install dasht and work ok on shell, I've following the instruction to install the vim plugin and add this to my init.vim 

Search docsets for words under cursor:
" search related docsets
nnoremap <silent> <Leader>K :call Dasht([expand('<cword>'), expand('<cWORD>')])<Return>

when I try to press \\K and it show "Not an Editor command: Dasht"

**Comment by justinmk** [comment]
has nothing to do with Neovim.

**Comment by philipatc** [comment]
understand, Thanks

**Comment by sunaku** [comment]
This appears to be an installation problem. :thinking: Which (Neo)Vim plugin manager are you using?

Simply adding this git repo's cloned location to your Vim `&runtimepath` should be enough.

Otherwise, you could also try manually `:source` each of the `*.vim` files inside this git repo.

**Comment by sunaku** [comment]
Closing due to lack of response. :policeman: Please re-open if you still need help.
