### ISSUE TITLE
 Undefined variable: g:dasht_filetype_docsets

### ISSUE THREAD

**Issue by laoshaw** [sunaku/vim-dasht#14]
E121: Undefined variable: g:dasht_filetype_docsets

this variable can not be used with vim8.2.

**Comment by sunaku** [comment]
Hi @laoshaw, does this issue no longer occur for you? :thinking: I'm curious about why you closed the issue.

**Comment by laoshaw** [comment]
I tried to do : `let g:dasht_filetype_docsets['html'] = ['css', 'js', 'bootstrap']` under vim, now it says : `E689: Can only index a List, Dictionary or Blob`.

so the problem persists, I probably should not close it.

**Comment by sunaku** [comment]
Okay, I see the problem now: you need to first define the variable before you add entries to it:

```vim
let g:dasht_filetype_docsets = {} " filetype => list of docset name regexp
```

This is the first line in the example snippet in the README.  Maybe you forgot to copy/paste it.

**Comment by laoshaw** [comment]
Thanks. This fixed it it seems.
