### ISSUE TITLE
Set tab title to search term

### ISSUE THREAD

**Issue by hoschi** [sunaku/vim-dasht#2]
At the moment the tab title is "null || dasht 'padding' 'javascript' 'chai' 'css' ..... (list of docsets" which is pretty unusable, because the tabline gets full quickly.

Just set the tab title to the search term would really great. I read [your comment on reddit](https://www.reddit.com/r/neovim/comments/4jvjpf/vimdasht_neovim_plugin_for_dasht_integration/d3a3cla?context=3), that you don't know how to do that in vim. Unfortunately I also don't know VimL, but I have a suggestion where to search: [vim-ctrlspace/vim-ctrlspace](https://github.com/vim-ctrlspace/vim-ctrlspace) has a method to set tab title, but this doesn't work in NeoVim. Perhaps this is just a bug in NeoVim.

**Comment by sunaku** [comment]
This looks promising: https://github.com/neovim/neovim/issues/2488#issuecomment-95741234 :pray:

**Comment by hoschi** [comment]
Great

**Comment by sunaku** [comment]
Implemented in commit 82fac2cb6a61d0cd5889fa6b6431765ab5567b8e. :gift:  Thanks to @joushou  in https://github.com/neovim/neovim/issues/2488#issuecomment-95854651. :neckbeard:

**Comment by hoschi** [comment]
Works like a charm, thanks :)
