### ISSUE TITLE
Trouble executing `:Dasht`

### ISSUE THREAD

**Issue by chopfitzroy** [sunaku/vim-dasht#4]
When I execute `:Dasht` I get the following:

```vim
:Dasht                                                                                                                                                                 
E79: Cannot expand wildcards                                                                                                                                           
"''"  line 1 of 39 --2%-- col 1
```

If I press enter it works but I don't think I should be getting it?

Cheers,
Otis.

**Comment by sunaku** [comment]
Which version of Vim are you using?

What is your output of `:set shell?`

What operating system are you using?

**Comment by chopfitzroy** [comment]
Hey @sunaku I am using [Neovim](https://neovim.io/) `NVIM 0.2.0-dev`.

Output of `:set shell` is `shell=/usr/bin/fish` ([Fish Shell](https://fishshell.com/))

OS: Ubuntu 16.04

**Comment by sunaku** [comment]
Ah! It must be the Fish shell. :tropical_fish: Please check whether `:set shell=/bin/sh` fixes the problem.

**Comment by chopfitzroy** [comment]
Sweet fixed :)
