### ISSUE TITLE
Does not work on gvim

### ISSUE THREAD

**Issue by lervag** [sunaku/vim-dasht#6]
I understand that you use some voodoo to make this plugin work for Vim in terminal, however, it does not work on gui Vim.

I think a solution could be to allow the `dasht` command to work non-interactively, and simply redirect the output of a dasht command to an empty buffer. Perhaps add some simple syntax highlighting. This would be easy to make work in any Vim, I think.

What do you think?

**Comment by sunaku** [comment]
Try the new **gvim** branch, which launches an `xterm` in the background for interactivity.

Feel free to send a PR for your non-interactive usage idea.  :fearful: It's too much work for me.

**Comment by sunaku** [comment]
Fix is now available in **master** branch. :cake:  Thanks for reporting this issue. :+1:  Closing.

**Comment by lervag** [comment]
Great, thanks!
