### ISSUE TITLE
Handle several filetypes of file

### ISSUE THREAD

**Issue by petRUShka** [sunaku/vim-dasht#9]
Suppose I have file `fils.sage` which is Sage file (computer algebra system based on Python). In vim it has two filetypes: `sage` and `python`: `filetype=sage.python`.

If I try to use dasht-vim I catch an error: `dasht: 'loadtxt' not found in sage.python docsets`.

Whereas in bash `dasht loadtxt` works as expected (I've installed NumPy docses).

I think it would be useful to try to find firstly `sage.python` docests, then `sage` docset and then `python` docset instead of just the first one.

**Comment by sunaku** [comment]
Thanks for reporting this issue. 👍  Please try the fix I pushed to the **issue-9** branch.

**Comment by petRUShka** [comment]
That works great at the moment. Thanks!
